-   name: Installing NGINX web server
    apt:
        name: nginx
        state: present

-   name: Creating vhost directories
    file:
        path: "{{ nginxroot }}/{{ vhostdir }}"
        state: directory

-   name: Updating nginx configuration
    template:
        src: conf.j2
        dest: "{{ nginxroot }}/nginx.conf"
    notify: reload nginx

-   name: Updating NGINX proxy params
    template:
        src: params.j2
        dest: "{{ nginxroot }}/proxy_params"
    notify: reload nginx

-   name: Deleting obsolete directories
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - "{{ nginxroot }}/sites-available"
        - "{{ nginxroot }}/sites-enabled"
    notify: restart nginx
