-   name: Install nginx
    apt:
        name: nginx
        state: present

-   name: Create vhost dir
    file:
        path: "/etc/nginx/{{ vhostdir }}"
        state: directory

-   name: Update nginx conf
    template:
        src: conf.j2
        dest: /etc/nginx/nginx.conf

-   name: Delete obsolete dirs
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled
    notify: restart nginx
