-   name: Install nginx
    apt:
        name: nginx
        state: present

-   name: Create vhost dir
    file:
        path: "{{ nginxroot }}/{{ vhostdir }}"
        state: directory

-   name: Update nginx conf
    template:
        src: conf.j2
        dest: "{{ nginxroot }}/nginx.conf"
    notify: reload nginx

-   name: Update nginx proxy params
    template:
        src: params.j2
        dest: "{{ nginxroot }}/proxy_params"
    notify: reload nginx

-   name: Delete obsolete dirs
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - "{{ nginxroot }}/sites-available"
        - "{{ nginxroot }}/sites-enabled"
    notify: restart nginx
