-   name: Installing NGINX web server
    apt:
        name: nginx
        state: present

-   name: Creating vhost directories
    file:
        path: "{{ nginxroot }}/{{ vhostdir }}"
        state: directory

-   name: Updating NGINX configuration
    template:
        src: conf.j2
        dest: "{{ nginxroot }}/nginx.conf"
    notify: reload nginx

-   name: Updating NGINX proxy params
    template:
        src: params.j2
        dest: "{{ nginxroot }}/proxy_params"
    notify: reload nginx

-   name: Configuring default server vhost
    template:
        src: defaultserver.j2
        dest: "{{ nginxroot }}/conf.d/default.conf"
    notify: reload nginx

-   name: Deleting obsolete directories
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - "{{ nginxroot }}/sites-available"
        - "{{ nginxroot }}/sites-enabled"
    notify: restart nginx

-   name: Installing Certbot NGINX plugin
    apt:
        name: python-certbot-nginx 
        state: present
