-   name: Installing Apache web server
    apt:
        name: apache2
        state: present

-   name: Creating vhost directory
    file:
        path: "{{ apacheroot }}/{{ vhostdir }}"
        state: directory

-   name: Updating Apache configuration
    template:
        src: conf.j2
        dest: "{{ apacheroot }}/apache.conf"
    notify: restart apache

-   name: Updating ports configuration
    template:
        src: ports.j2
        dest: "{{ apacheroot }}/ports.conf"
    notify: restart apache

-   name: Deleting obsolete directories
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - "{{ apacheroot }}/sites-available"
        - "{{ apacheroot }}/sites-enabled"
    notify: restart apache
