-   name: Installing Apache web server
    apt:
        name: apache2
        state: present

-   name: Installing some needed modules
    apt:
        name: ["libapache2-mod-fcgid"]
        state: present
    notify: restart apache

-   name: Creating vhost directory
    file:
        path: "{{ apacheroot }}/{{ vhostdir }}"
        state: directory

-   name: Updating Apache configuration
    template:
        src: conf.j2
        dest: "{{ apacheroot }}/apache2.conf"
    notify: restart apache

-   name: Deleting obsolete directories
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - "{{ apacheroot }}/sites-available"
        - "{{ apacheroot }}/sites-enabled"
    notify: restart apache

-   name: Enabling Apache rewrite module
    apache2_module:
        name: ["rewrite", "ssl"]
        state: present

-   name: Enabling mod_expires module
    apache2_module:
        name: expires
        state: present

-   name: Enabling Apache proxy_fcgi module
    apache2_module:
        name: proxy_fcgi
        state: present

-   name: Installing Certbot Apache plugin
    apt:
        name: python-certbot-apache
        state: present

-   name: Restarting Apache
    service:
        name: apache2
        state: restarted
