-   name: Install apache
    apt:
        name: apache2
        state: present

-   name: Create vhost dir
    file:
        path: "/etc/apache2/{{ vhostdir }}"
        state: directory

-   name: Update apache conf
    template:
        src: conf.j2
        dest: /etc/apache2/apache.conf

-   name: Update ports conf
    template:
        src: ports.j2
        dest: /etc/ports.conf

-   name: Delete obsolete dirs
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - /etc/apache2/sites-available
        - /etc/apache2/sites-enabled
    notify: restart apache
