-   name: Installing required libraries
    apt:
        name: ["python3", "python3-pip"]
        state: present

-   name: Ensure locale is in tact
    command: {{ item }}
    with_items:
        -   export LC_ALL="en_US.UTF-8"
        -   export LC_CTYPE="en_US.UTF-8"
        -   dpkg-reconfigure locales

-   name: Creating web root directory
    file:
        path: "{{ webroot }}"
        state: directory

-   name: Create default serverpack group
    group:
        name: "{{ defaultgroup }}"
        state: present

-   name: Configuring ACL for root user
    acl:
        path: "{{ webroot }}"
        entity: root
        etype: user
        permissions: rwx
        recursive: yes
        state: present

-   name: Configuring ACL for serverpack group
    acl:
        path: "{{ webroot }}"
        entity: "{{ defaultgroup }}"
        etype: group
        permissions: x
        recursive: yes
        state: present
