-   name: Installing required libraries
    apt:
        name: ["python3", "python3-pip"]
        state: present

-   name: Setting default locale
    lineinfile:
        dest: /etc/default/locale
        regexp: "LC_ALL"
        line: LC_ALL="en_US.UTF-8"

-   name: Creating web root directory
    file:
        path: "{{ webroot }}"
        state: directory

-   name: Create default serverpack group
    group:
        name: "{{ defaultgroup }}"
        state: present

-   name: Configuring ACL for root user
    acl:
        path: "{{ webroot }}"
        entity: root
        etype: user
        permissions: rwx
        recursive: yes
        state: present

-   name: Configuring ACL for serverpack group
    acl:
        path: "{{ webroot }}"
        entity: "{{ defaultgroup }}"
        etype: group
        permissions: x
        recursive: yes
        state: present
