-   name: Create web root
    file:
        path: "{{ webroot }}"
        state: directory

-   name: Create default group
    group:
        name: "{{ defaultgroup }}"
        state: present

-   name: Configuring ACL for root
    acl:
        path: "{{ webroot }}"
        entity: root
        etype: user
        permissions: rwx
        recursive: yes
        state: present

-   name: Configuring ACL for serverpack group
    acl:
        path: "{{ webroot }}"
        entity: "{{ defaultgroup }}"
        etype: group
        permissions: x
        recursive: yes
        state: present
