-   name: Specify MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_pass | quote}}' vtype='password'

-   name: Confirming MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_pass | quote}}' vtype='password'

-   name: Installing MySQL server
    apt:
        name: ["mysql-server"]
        state: present

-   name: Generating conf file
    template:
        src: cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600
    notify: start mysql

-   name: Updating root password
    mysql_user: name=root password={{ mysql_root_pass }} priv=*.*:ALL,GRANT

-   name: Removing annonymous MySQL users
    mysql_user: name="" host={{ item }} state=absent
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

-   name: Removing the test MySQL database
    mysql_db:
        name: test
        state: absent
    notify: restart mysql

-   name: Configuring phpMyAdmin installation
    debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

-   name: Configuring phpMyAdmin to use MySQl root password
    debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{mysql_root_pass}}' vtype='password'

-   name: Configuring phpMyAdmin to use MySQl root password
    debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql_root_pass}}' vtype='password'

-   name: Configuring phpMyAdmin to use MySQl root password
    debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{mysql_root_pass}}' vtype='password'

-   name: Configuring webserver to serve phpMyAdmin
    debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

-   name: Installing phpMyAdmin
    apt:
        name: phpmyadmin
        state: present

-   name: Enabling phpMyAdmin vhost
    file:
        path: "{{ apacheroot }}/{{ vhostdir }}/pma.conf"
        src: /etc/phpmyadmin/apache.conf
        state: link

-   name: Reloading Apache server
    service:
        name: apache2
        state: reloaded
