-   name: Installing MySQL Python module (Required)
    pip:
        name: MySQL-python
        executable: pip3

-   name: Installing MySQL server
    apt:
        name: ["mysql", "mysql-server"]
        state: present

-   name: Updaging root password
    mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} priv=*.*:ALL,GRANT
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

-   name: Generating conf file
    template:
        src: cnf.j2 dest=/root/.my.cnf
        owner: root
        mode: 0600
    notify: start mysql
