-   name: Specify MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_pass | quote}}' vtype='password'

-   name: Confirming MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_pass | quote}}' vtype='password'

-   name: Installing MySQL server
    apt:
        name: ["mysql-server"]
        state: present

-   name: Updating root password
    mysql_user: name=root host_all=yes password={{ mysql_root_pass }} priv=*.*:ALL,GRANT

-   name: Generating conf file
    template:
        src: cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600
    notify: start mysql

-   name: Removing annonymous MySQL users
    mysql_user: name="" host={{ item }} state=absent
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

-   name: Removing the test MySQL database
    mysql_db:
        name: test
        state: absent
    notify: restart mysql
