-   name: Installing MySQL Python module (Required)
    pip:
        name: MySQL-python

-   name: Installing MySQL server
    apt:
        name: ["mysql-server"]
        state: present

-   name: Updaging root password
    mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} priv=*.*:ALL,GRANT
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

-   name: Generating conf file
    template:
        src: cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600
    notify: start mysql

-   name: Removing annonymous MySQL users
    mysql_user: name="" host={{ item }} state=absent
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

-   name: Removing the test MySQL database
    mysql_db:
        name: test
        state: absent
        login_host: "{{ item }}"
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
    notify: restart mysql
