-   name: "Configuring firewall"
    ufw:
        state: enabled
        direction: incoming
        policy: deny

-   name: "Opening needed ports"
    ufw:
        rule: allow
        proto: tcp
        port: "{{ item }}"
    with_items:
        - "{{ allowedports }}"
