---
repourl: https://github.com/rehmatworks/serverpack
projectname: sp
sproot: /etc/serverpack
cproot: "{{ sproot }}/cp"
venvroot: "{{ sproot }}/spvenv"
gunicornservice: serverpack
spsslroot: "{{ sproot }}/ssl"
privkeypath: "{{ spsslroot }}/privkey.pem"
csrpath: "{{ spsslroot }}/csr.pem"
crtpath: "{{ spsslroot }}/sp.pem"
