-   name: Importing ppa:ondrej/php PPA for multiple PHP version support
    apt_repository:
        repo: ppa:ondrej/php
        state: present

-   name: Updating packages
    apt:
        update_cache: yes

-   name: Installing selected PHP versions
    apt:
        name: "php{{ item }}"
        state: present
    with_items:
        - "{{ phpversions }}"

-   name: Installing PHP 5.6 modules
    apt:
        name: ['php5.6-{{ phpmodules }}']
        state: present
    with_items:
        - "{{ phpmodules }}"

-   name: Installing PHP 7.0 modules
    apt:
        name: ['php7.0-{{ phpmodules }}']
        state: present
    with_items:
        - "{{ phpmodules }}"

-   name: Installing PHP 7.1 modules
    apt:
        name: ['php7.1-{{ phpmodules }}']
        state: present
    with_items:
        - "{{ phpmodules }}"

-   name: Installing PHP 7.2 modules
    apt:
        name: ['php7.2-{{ phpmodules }}']
        state: present
    with_items:
        - "{{ phpmodules }}"

-   name: Installing PHP 7.3 modules
    apt:
        name: ['php7.3-{{ phpmodules }}']
        state: present
    with_items:
        - "{{ phpmodules }}"

-   name: Installing PHP-FPM
    apt:
        name: "php{{ item }}-fpm"
        state: present
    with_items:
        - "{{ phpversions }}"

-   name: Updating selected PHP ini values
    template:
        src: 10-serverpack.j2
        dest: /etc/php/{{ item }}/fpm/conf.d/10-serverpack.ini
    with_items:
        - "{{ phpversions }}"
    notify: reload php {{ item }}

-   name: Updating PHP-FPM configuration
    template:
        src: fpmconf.j2
        dest: /etc/php/{{ item }}/fpm/php-fpm.conf
    with_items:
        - "{{ phpversions }}"
    notify: reload php {{ item }}
