---
-   name: rebuild locales database
    command: "{{ item }}"
    with_items:
        - dpkg-reconfigure locales -f noninteractive
        - /usr/sbin/locale-gen

-   name: restart_sshd
    service:
        name: sshd
        state: restarted
